// Generated by https://quicktype.io

namespace Core.Interfaces
{
    public interface IHitPackage
    {
        object FinishedJudgmentData { get; set; }
        object HitData { get; set; }
        long HitDataInt { get; set; }
        string HitDataXml { get; set; }
        long HitGroupDataInt { get; set; }
        object HitGroupDataXml { get; set; }
        long HitGroupId { get; set; }
        long HitId { get; set; }
        long HitType { get; set; }
        bool IsBouncy { get; set; }
        bool IsCrowdSourcing { get; set; }
        bool IsGoldHit { get; set; }
        long JudgmentDataInt { get; set; }
        object JudgmentDataXml { get; set; }
        long JudgmentId { get; set; }
        long LeasedCount { get; set; }
        string LeaseExpireTime { get; set; }
        long LeaseTime { get; set; }
        bool PreviewOnly { get; set; }
        long Price { get; set; }
        object[] PropertyBag { get; set; }
        object RealTimeAudit { get; set; }
        long ReputationScore { get; set; }
        long SatelliteId { get; set; }

        long SuggestedGoldHitTypeId { get; set; }
        long TaskGroupId { get; set; }
        long TimeSpentOnJudgment { get; set; }
        string Type { get; set; }
    }
}
