// Generated by https://quicktype.io

namespace Core.Interfaces
{
    public interface IServerDetails
    {
        string Message { get; set; }
        string Type { get; set; }
        long Version { get; set; }
    }
}
